version: '2.1'
services:
  auth-proxy:
    image: xcode1024/auth-proxy:latest
    container_name: auth-proxy
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - frontend

  frontend:
    image: mwangxx/bulletjournal-frontend:1.1.2
    container_name: react_app
    ports:
      - "3000:3000"
    depends_on:
      - controller

  controller:
    image: mwangxx/bulletjournal-backend:1.1.2
    container_name: springboot_app
    ports:
      - "8080:8080"
    environment:
      spring_profiles_active: prod
      SSO_API_KEY: "${SSO_API_KEY}"
    volumes:
      - $HOME/docker/volumes/log:/var/log
    depends_on:
      database:
        condition: service_healthy

  cache:
    image: redis
    container_name: cache
    ports:
      - "127.0.0.1:6379:6379"

  database:
    image: postgres
    container_name: db
    hostname: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: postgres
    volumes:
      - $HOME/docker/volumes/postgres:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5