USERNAME: postgres
PASSWORD: docker
DATABASE: postgres
DBPORT: 5432
RPCPORT: 50051
HTTPPORT: 9091
HOST: database
DBDRIVER: postgresql
APIKEYPUBLIC: MJ_APIKEY_PUBLIC_DAEMON
APIKEYPRIVATE: MJ_APIKEY_PRIVATE_DAEMON
SENDEREMAIL: DAEMON_SENDER_EMAIL
SENDERNAME: SENDER_NAME